import { defineObject, FieldType } from 'twenty-sdk';
import {
  APPLICATION_OBJECT_ID,
  APPLICATION_DISPLAY_LABEL_FIELD_ID,
  APPLICATION_STAGE_FIELD_ID,
  APPLICATION_SOURCE_FIELD_ID,
  APPLICATION_APPLIED_AT_FIELD_ID,
  APPLICATION_RATING_FIELD_ID,
  APPLICATION_DISQUALIFY_REASON_FIELD_ID,
  APPLICATION_NOTES_FIELD_ID,
  APPLICATION_FIT_SCORE_FIELD_ID,
  APPLICATION_REASONING_FIT_SCORE_FIELD_ID,
  APPLICATION_FIT_SCORE_GENERATED_FIELD_ID,
  STAGE_TAGGED_INTERESTED_ID,
  STAGE_QUALIFYING_ID,
  STAGE_SCHEDULE_ID,
  STAGE_SUBMITTED_ID,
  STAGE_PHONE_SCREEN_ID,
  STAGE_SECOND_INTERVIEW_ID,
  STAGE_THIRD_INTERVIEW_ID,
  STAGE_FINAL_ID,
  STAGE_OFFER_ID,
  STAGE_REJECTED_PULLED_ID,
  SOURCE_REFERRAL_ID,
  SOURCE_SOURCED_ID,
  SOURCE_CAREER_PAGE_ID,
  SOURCE_INBOUND_ID,
  SOURCE_OTHER_ID,
  RATING_STRONG_YES_ID,
  RATING_YES_ID,
  RATING_NO_ID,
  RATING_STRONG_NO_ID,
  DISQUALIFY_SKILLS_MISMATCH_ID,
  DISQUALIFY_CULTURE_MISMATCH_ID,
  DISQUALIFY_COMPENSATION_ID,
  DISQUALIFY_WITHDREW_ID,
  DISQUALIFY_OTHER_ID,
} from 'src/constants';

// Application = join record between a Person (candidate) and a Position.
// Holds the per-role lifecycle: stage, dates, rating, source, disqualify reason.
// Label is composed by the set-application-display-label logic function.
export default defineObject({
  universalIdentifier: APPLICATION_OBJECT_ID,
  // GraphQL/event name = nameSingular. Twenty's core has its own `application`
  // object (installed apps), so we use `jobApplication` to avoid event-routing
  // collisions while keeping "Application" as the recruiter-facing label.
  nameSingular: 'jobApplication',
  namePlural: 'jobApplications',
  labelSingular: 'Candidate',
  labelPlural: 'Candidates',
  description: 'A candidate applying to a specific position',
  icon: 'IconUserCheck',
  labelIdentifierFieldMetadataUniversalIdentifier:
    APPLICATION_DISPLAY_LABEL_FIELD_ID,
  fields: [
    {
      universalIdentifier: APPLICATION_DISPLAY_LABEL_FIELD_ID,
      type: FieldType.TEXT,
      name: 'displayLabel',
      label: 'Label',
      description:
        'Auto-composed "{candidate} — {position}". Set by the display-label logic function; do not edit manually.',
      icon: 'IconTag',
    },
    {
      universalIdentifier: APPLICATION_STAGE_FIELD_ID,
      type: FieldType.SELECT,
      name: 'stage',
      label: 'Stage',
      description: 'Current pipeline stage',
      icon: 'IconListCheck',
      defaultValue: "'TAGGED_INTERESTED'",
      options: [
        { id: STAGE_TAGGED_INTERESTED_ID, value: 'TAGGED_INTERESTED', label: 'Tagged/Interested', position: 0, color: 'blue' },
        { id: STAGE_QUALIFYING_ID, value: 'QUALIFYING', label: 'Qualifying', position: 1, color: 'sky' },
        { id: STAGE_SCHEDULE_ID, value: 'SCHEDULE', label: 'Schedule', position: 2, color: 'turquoise' },
        { id: STAGE_SUBMITTED_ID, value: 'SUBMITTED', label: 'Submitted', position: 3, color: 'purple' },
        { id: STAGE_PHONE_SCREEN_ID, value: 'PHONE_SCREEN', label: 'Phone Screen', position: 4, color: 'pink' },
        { id: STAGE_SECOND_INTERVIEW_ID, value: 'SECOND_INTERVIEW', label: '2nd Interview', position: 5, color: 'orange' },
        { id: STAGE_THIRD_INTERVIEW_ID, value: 'THIRD_INTERVIEW', label: '3rd Interview', position: 6, color: 'yellow' },
        { id: STAGE_FINAL_ID, value: 'FINAL', label: 'Final', position: 7, color: 'green' },
        { id: STAGE_OFFER_ID, value: 'OFFER', label: 'Offer', position: 8, color: 'green' },
        { id: STAGE_REJECTED_PULLED_ID, value: 'REJECTED_PULLED_OUT', label: 'Rejected/Pulled Out of Process', position: 9, color: 'red' },
      ],
    },
    {
      universalIdentifier: APPLICATION_SOURCE_FIELD_ID,
      type: FieldType.SELECT,
      name: 'source',
      label: 'Source',
      description: 'How this candidate came in for this role',
      icon: 'IconRoute',
      isNullable: true,
      defaultValue: null,
      options: [
        { id: SOURCE_REFERRAL_ID, value: 'REFERRAL', label: 'Referral', position: 0, color: 'green' },
        { id: SOURCE_SOURCED_ID, value: 'SOURCED', label: 'Sourced', position: 1, color: 'purple' },
        { id: SOURCE_CAREER_PAGE_ID, value: 'CAREER_PAGE', label: 'Career page', position: 2, color: 'blue' },
        { id: SOURCE_INBOUND_ID, value: 'INBOUND', label: 'Inbound', position: 3, color: 'sky' },
        { id: SOURCE_OTHER_ID, value: 'OTHER', label: 'Other', position: 4, color: 'gray' },
      ],
    },
    {
      universalIdentifier: APPLICATION_APPLIED_AT_FIELD_ID,
      type: FieldType.DATE_TIME,
      name: 'appliedAt',
      label: 'Applied at',
      description: 'When the candidate applied (defaults to created time)',
      icon: 'IconCalendar',
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: APPLICATION_RATING_FIELD_ID,
      type: FieldType.SELECT,
      name: 'rating',
      label: 'Rating',
      description: 'Overall hiring-bar signal from the panel',
      icon: 'IconThumbUp',
      isNullable: true,
      defaultValue: null,
      options: [
        { id: RATING_STRONG_YES_ID, value: 'STRONG_YES', label: 'Strong yes', position: 0, color: 'green' },
        { id: RATING_YES_ID, value: 'YES', label: 'Yes', position: 1, color: 'turquoise' },
        { id: RATING_NO_ID, value: 'NO', label: 'No', position: 2, color: 'orange' },
        { id: RATING_STRONG_NO_ID, value: 'STRONG_NO', label: 'Strong no', position: 3, color: 'red' },
      ],
    },
    {
      universalIdentifier: APPLICATION_DISQUALIFY_REASON_FIELD_ID,
      type: FieldType.SELECT,
      name: 'disqualifyReason',
      label: 'Disqualify reason',
      description: 'Why the candidate was disqualified (only meaningful when stage = Disqualified)',
      icon: 'IconX',
      isNullable: true,
      defaultValue: null,
      options: [
        { id: DISQUALIFY_SKILLS_MISMATCH_ID, value: 'SKILLS_MISMATCH', label: 'Skills mismatch', position: 0, color: 'orange' },
        { id: DISQUALIFY_CULTURE_MISMATCH_ID, value: 'CULTURE_MISMATCH', label: 'Culture mismatch', position: 1, color: 'purple' },
        { id: DISQUALIFY_COMPENSATION_ID, value: 'COMPENSATION', label: 'Compensation', position: 2, color: 'yellow' },
        { id: DISQUALIFY_WITHDREW_ID, value: 'WITHDREW', label: 'Candidate withdrew', position: 3, color: 'gray' },
        { id: DISQUALIFY_OTHER_ID, value: 'OTHER', label: 'Other', position: 4, color: 'gray' },
      ],
    },
    {
      universalIdentifier: APPLICATION_NOTES_FIELD_ID,
      type: FieldType.RICH_TEXT,
      name: 'notes',
      label: 'Notes',
      description: 'Per-application notes (separate from the candidate-level notes on the Person record)',
      icon: 'IconNotes',
    },
    {
      universalIdentifier: APPLICATION_FIT_SCORE_FIELD_ID,
      type: FieldType.NUMBER,
      name: 'fitScore',
      label: 'Fit score',
      description: 'Candidate fit score for this position (percentage)',
      icon: 'IconPercentage',
      isNullable: true,
      defaultValue: null,
      universalSettings: {
        dataType: 'float',
        decimals: 2,
        type: 'percentage',
      } as never,
    },
    {
      universalIdentifier: APPLICATION_REASONING_FIT_SCORE_FIELD_ID,
      type: FieldType.TEXT,
      name: 'reasoningFitScore',
      label: 'Reasoning for fit score',
      description: 'Explanation behind the fit score',
      icon: 'IconMessage',
    },
    {
      universalIdentifier: APPLICATION_FIT_SCORE_GENERATED_FIELD_ID,
      type: FieldType.BOOLEAN,
      name: 'fitScoreGenerated',
      label: 'Fit score generated',
      description: 'Whether a fit score has been generated for this application',
      icon: 'IconCheck',
      defaultValue: false,
    },
  ],
});
