import { defineObject, FieldType } from 'twenty-sdk';
import {
  POSITION_OBJECT_ID,
  POSITION_NAME_FIELD_ID,
  POSITION_DEPARTMENT_FIELD_ID,
  POSITION_LOCATION_FIELD_ID,
  POSITION_EMPLOYMENT_TYPE_FIELD_ID,
  POSITION_DESCRIPTION_FIELD_ID,
  POSITION_STATUS_FIELD_ID,
  POSITION_OPENED_AT_FIELD_ID,
  POSITION_CLOSED_AT_FIELD_ID,
  POSITION_SCORING_FRAMEWORK_FIELD_ID,
  DEPT_ENGINEERING_ID,
  DEPT_DESIGN_ID,
  DEPT_PRODUCT_ID,
  DEPT_GTM_ID,
  DEPT_OPS_ID,
  DEPT_OTHER_ID,
  EMPLOYMENT_FULL_TIME_ID,
  EMPLOYMENT_PART_TIME_ID,
  EMPLOYMENT_CONTRACT_ID,
  EMPLOYMENT_INTERNSHIP_ID,
  POSITION_STATUS_DRAFT_ID,
  POSITION_STATUS_OPEN_ID,
  POSITION_STATUS_ON_HOLD_ID,
  POSITION_STATUS_CLOSED_ID,
} from 'src/constants';

export default defineObject({
  universalIdentifier: POSITION_OBJECT_ID,
  // GraphQL type name = nameSingular capitalized; "Position" collides with a
  // built-in Twenty type, so the real name is "jobPosition" with display labels
  // kept as "Position" so recruiters see the natural word in the UI.
  nameSingular: 'jobPosition',
  namePlural: 'jobPositions',
  labelSingular: 'Position',
  labelPlural: 'Positions',
  description: 'An open role you are hiring for',
  icon: 'IconBriefcase',
  labelIdentifierFieldMetadataUniversalIdentifier: POSITION_NAME_FIELD_ID,
  fields: [
    {
      universalIdentifier: POSITION_NAME_FIELD_ID,
      type: FieldType.TEXT,
      name: 'name',
      label: 'Title',
      description: 'Job title (e.g., "Staff Engineer")',
      icon: 'IconAbc',
    },
    {
      universalIdentifier: POSITION_DEPARTMENT_FIELD_ID,
      type: FieldType.SELECT,
      name: 'department',
      label: 'Department',
      description: 'Team or department the role belongs to',
      icon: 'IconBuildingCommunity',
      isNullable: true,
      defaultValue: null,
      options: [
        { id: DEPT_ENGINEERING_ID, value: 'ENGINEERING', label: 'Engineering', position: 0, color: 'blue' },
        { id: DEPT_DESIGN_ID, value: 'DESIGN', label: 'Design', position: 1, color: 'purple' },
        { id: DEPT_PRODUCT_ID, value: 'PRODUCT', label: 'Product', position: 2, color: 'turquoise' },
        { id: DEPT_GTM_ID, value: 'GTM', label: 'Go-to-Market', position: 3, color: 'orange' },
        { id: DEPT_OPS_ID, value: 'OPS', label: 'Operations', position: 4, color: 'yellow' },
        { id: DEPT_OTHER_ID, value: 'OTHER', label: 'Other', position: 5, color: 'gray' },
      ],
    },
    {
      universalIdentifier: POSITION_LOCATION_FIELD_ID,
      type: FieldType.TEXT,
      name: 'location',
      label: 'Location',
      description: 'Role location (e.g., "Remote (US)", "NYC")',
      icon: 'IconMapPin',
    },
    {
      universalIdentifier: POSITION_EMPLOYMENT_TYPE_FIELD_ID,
      type: FieldType.SELECT,
      name: 'employmentType',
      label: 'Employment type',
      description: 'Full-time, part-time, contract, or internship',
      icon: 'IconClock',
      isNullable: true,
      defaultValue: "'FULL_TIME'",
      options: [
        { id: EMPLOYMENT_FULL_TIME_ID, value: 'FULL_TIME', label: 'Full-time', position: 0, color: 'green' },
        { id: EMPLOYMENT_PART_TIME_ID, value: 'PART_TIME', label: 'Part-time', position: 1, color: 'yellow' },
        { id: EMPLOYMENT_CONTRACT_ID, value: 'CONTRACT', label: 'Contract', position: 2, color: 'orange' },
        { id: EMPLOYMENT_INTERNSHIP_ID, value: 'INTERNSHIP', label: 'Internship', position: 3, color: 'sky' },
      ],
    },
    {
      universalIdentifier: POSITION_DESCRIPTION_FIELD_ID,
      type: FieldType.RICH_TEXT,
      name: 'description',
      label: 'Job description',
      description: 'Job description / posting body',
      icon: 'IconFileDescription',
    },
    {
      universalIdentifier: POSITION_STATUS_FIELD_ID,
      type: FieldType.SELECT,
      name: 'status',
      label: 'Status',
      description: 'Hiring status for this role',
      icon: 'IconFlag',
      defaultValue: "'DRAFT'",
      options: [
        { id: POSITION_STATUS_DRAFT_ID, value: 'DRAFT', label: 'Draft', position: 0, color: 'gray' },
        { id: POSITION_STATUS_OPEN_ID, value: 'OPEN', label: 'Open', position: 1, color: 'green' },
        { id: POSITION_STATUS_ON_HOLD_ID, value: 'ON_HOLD', label: 'On hold', position: 2, color: 'yellow' },
        { id: POSITION_STATUS_CLOSED_ID, value: 'CLOSED', label: 'Closed', position: 3, color: 'red' },
      ],
    },
    {
      universalIdentifier: POSITION_OPENED_AT_FIELD_ID,
      type: FieldType.DATE_TIME,
      name: 'openedAt',
      label: 'Opened at',
      description: 'When the role moved to Open status',
      icon: 'IconCalendarPlus',
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: POSITION_CLOSED_AT_FIELD_ID,
      type: FieldType.DATE_TIME,
      name: 'closedAt',
      label: 'Closed at',
      description: 'When the role moved to Closed status',
      icon: 'IconCalendarMinus',
      isNullable: true,
      defaultValue: null,
    },
    {
      universalIdentifier: POSITION_SCORING_FRAMEWORK_FIELD_ID,
      type: FieldType.RICH_TEXT,
      name: 'scoringFramework',
      label: 'Scoring framework',
      description: 'Rubric used to evaluate candidates for this role (markdown supported)',
      icon: 'IconChecklist',
    },
  ],
});
