import { defineView, ViewKey } from 'twenty-sdk';
import {
  VIEW_APPLICATIONS_ALL_ID,
  APPLICATION_OBJECT_ID,
  APPLICATION_DISPLAY_LABEL_FIELD_ID,
  APPLICATION_POSITION_FIELD_ID,
  APPLICATION_CANDIDATE_FIELD_ID,
  APPLICATION_STAGE_FIELD_ID,
  APPLICATION_RATING_FIELD_ID,
  APPLICATION_APPLIED_AT_FIELD_ID,
  APPLICATION_SOURCE_FIELD_ID,
  APPLICATION_NOTES_FIELD_ID,
  APPLICATION_FIT_SCORE_FIELD_ID,
  APPLICATION_FIT_SCORE_GENERATED_FIELD_ID,
  APPLICATION_REASONING_FIT_SCORE_FIELD_ID,
  VF_ALL_LABEL,
  VF_ALL_POSITION,
  VF_ALL_CANDIDATE,
  VF_ALL_STAGE,
  VF_ALL_RATING,
  VF_ALL_APPLIED_AT,
  VF_ALL_SOURCE,
  VF_ALL_NOTES,
  VF_ALL_FIT_SCORE,
  VF_ALL_FIT_SCORE_GENERATED,
  VF_ALL_REASONING_FIT_SCORE,
  VG_ALL_TAGGED_INTERESTED,
  VG_ALL_QUALIFYING,
  VG_ALL_SCHEDULE,
  VG_ALL_SUBMITTED,
  VG_ALL_PHONE_SCREEN,
  VG_ALL_SECOND_INTERVIEW,
  VG_ALL_THIRD_INTERVIEW,
  VG_ALL_FINAL,
  VG_ALL_OFFER,
  VG_ALL_REJECTED_PULLED,
} from 'src/constants';

// Kanban grouped by stage. The SDK's ViewManifest type doesn't expose
// mainGroupByFieldMetadataUniversalIdentifier, so the stage→column wiring is
// completed by the post-install setup-kanban.sh script (which UPDATEs the view
// row's mainGroupByFieldMetadataId in the DB). The `type` below is declared as
// 'KANBAN' via a cast because ViewType isn't re-exported from twenty-sdk@0.9.0.
export default defineView({
  universalIdentifier: VIEW_APPLICATIONS_ALL_ID,
  name: 'All Candidates',
  objectUniversalIdentifier: APPLICATION_OBJECT_ID,
  icon: 'IconLayoutKanban',
  key: ViewKey.INDEX,
  type: 'KANBAN' as never,
  position: 0,
  fields: [
    {
      universalIdentifier: VF_ALL_LABEL,
      fieldMetadataUniversalIdentifier: APPLICATION_DISPLAY_LABEL_FIELD_ID,
      position: 0,
      isVisible: true,
      size: 280,
    },
    {
      universalIdentifier: VF_ALL_POSITION,
      fieldMetadataUniversalIdentifier: APPLICATION_POSITION_FIELD_ID,
      position: 1,
      isVisible: true,
      size: 200,
    },
    {
      universalIdentifier: VF_ALL_CANDIDATE,
      fieldMetadataUniversalIdentifier: APPLICATION_CANDIDATE_FIELD_ID,
      position: 2,
      isVisible: true,
      size: 200,
    },
    {
      universalIdentifier: VF_ALL_STAGE,
      fieldMetadataUniversalIdentifier: APPLICATION_STAGE_FIELD_ID,
      position: 3,
      isVisible: true,
      size: 130,
    },
    {
      universalIdentifier: VF_ALL_RATING,
      fieldMetadataUniversalIdentifier: APPLICATION_RATING_FIELD_ID,
      position: 4,
      isVisible: true,
      size: 120,
    },
    {
      universalIdentifier: VF_ALL_APPLIED_AT,
      fieldMetadataUniversalIdentifier: APPLICATION_APPLIED_AT_FIELD_ID,
      position: 5,
      isVisible: true,
      size: 140,
    },
    {
      universalIdentifier: VF_ALL_SOURCE,
      fieldMetadataUniversalIdentifier: APPLICATION_SOURCE_FIELD_ID,
      position: 6,
      isVisible: true,
      size: 130,
    },
    {
      universalIdentifier: VF_ALL_NOTES,
      fieldMetadataUniversalIdentifier: APPLICATION_NOTES_FIELD_ID,
      position: 7,
      isVisible: true,
      size: 200,
    },
    {
      universalIdentifier: VF_ALL_FIT_SCORE,
      fieldMetadataUniversalIdentifier: APPLICATION_FIT_SCORE_FIELD_ID,
      position: 8,
      isVisible: true,
      size: 110,
    },
    {
      universalIdentifier: VF_ALL_REASONING_FIT_SCORE,
      fieldMetadataUniversalIdentifier: APPLICATION_REASONING_FIT_SCORE_FIELD_ID,
      position: 9,
      isVisible: true,
      size: 220,
    },
    {
      universalIdentifier: VF_ALL_FIT_SCORE_GENERATED,
      fieldMetadataUniversalIdentifier: APPLICATION_FIT_SCORE_GENERATED_FIELD_ID,
      position: 10,
      isVisible: true,
      size: 140,
    },
  ],
  groups: [
    { universalIdentifier: VG_ALL_TAGGED_INTERESTED, fieldValue: 'TAGGED_INTERESTED', isVisible: true, position: 0 },
    { universalIdentifier: VG_ALL_QUALIFYING, fieldValue: 'QUALIFYING', isVisible: true, position: 1 },
    { universalIdentifier: VG_ALL_SCHEDULE, fieldValue: 'SCHEDULE', isVisible: true, position: 2 },
    { universalIdentifier: VG_ALL_SUBMITTED, fieldValue: 'SUBMITTED', isVisible: true, position: 3 },
    { universalIdentifier: VG_ALL_PHONE_SCREEN, fieldValue: 'PHONE_SCREEN', isVisible: true, position: 4 },
    { universalIdentifier: VG_ALL_SECOND_INTERVIEW, fieldValue: 'SECOND_INTERVIEW', isVisible: true, position: 5 },
    { universalIdentifier: VG_ALL_THIRD_INTERVIEW, fieldValue: 'THIRD_INTERVIEW', isVisible: true, position: 6 },
    { universalIdentifier: VG_ALL_FINAL, fieldValue: 'FINAL', isVisible: true, position: 7 },
    { universalIdentifier: VG_ALL_OFFER, fieldValue: 'OFFER', isVisible: true, position: 8 },
    { universalIdentifier: VG_ALL_REJECTED_PULLED, fieldValue: 'REJECTED_PULLED_OUT', isVisible: true, position: 9 },
  ],
});
