import { defineView, ViewKey } from 'twenty-sdk';
import {
  VIEW_POSITIONS_ALL_ID,
  POSITION_OBJECT_ID,
  POSITION_NAME_FIELD_ID,
  POSITION_DEPARTMENT_FIELD_ID,
  POSITION_LOCATION_FIELD_ID,
  POSITION_EMPLOYMENT_TYPE_FIELD_ID,
  POSITION_STATUS_FIELD_ID,
  POSITION_HIRING_MANAGER_FIELD_ID,
  POSITION_OPENED_AT_FIELD_ID,
  POSITION_DESCRIPTION_FIELD_ID,
  POSITION_SCORING_FRAMEWORK_FIELD_ID,
  POSITION_CREATED_AT_FIELD_ID,
  VF_POSITIONS_ALL_NAME,
  VF_POSITIONS_ALL_DEPT,
  VF_POSITIONS_ALL_LOCATION,
  VF_POSITIONS_ALL_EMPLOYMENT,
  VF_POSITIONS_ALL_STATUS,
  VF_POSITIONS_ALL_HIRING_MGR,
  VF_POSITIONS_ALL_OPENED_AT,
  VF_POSITIONS_ALL_DESCRIPTION,
  VF_POSITIONS_ALL_CREATED_AT,
  VF_POSITIONS_ALL_SCORING_FRAMEWORK,
} from 'src/constants';

export default defineView({
  universalIdentifier: VIEW_POSITIONS_ALL_ID,
  name: 'All Positions',
  objectUniversalIdentifier: POSITION_OBJECT_ID,
  icon: 'IconBriefcase',
  key: ViewKey.INDEX,
  position: 0,
  fields: [
    {
      universalIdentifier: VF_POSITIONS_ALL_NAME,
      fieldMetadataUniversalIdentifier: POSITION_NAME_FIELD_ID,
      position: 0,
      isVisible: true,
      size: 240,
    },
    {
      universalIdentifier: VF_POSITIONS_ALL_DEPT,
      fieldMetadataUniversalIdentifier: POSITION_DEPARTMENT_FIELD_ID,
      position: 1,
      isVisible: true,
      size: 140,
    },
    {
      universalIdentifier: VF_POSITIONS_ALL_LOCATION,
      fieldMetadataUniversalIdentifier: POSITION_LOCATION_FIELD_ID,
      position: 2,
      isVisible: true,
      size: 160,
    },
    {
      universalIdentifier: VF_POSITIONS_ALL_EMPLOYMENT,
      fieldMetadataUniversalIdentifier: POSITION_EMPLOYMENT_TYPE_FIELD_ID,
      position: 3,
      isVisible: true,
      size: 130,
    },
    {
      universalIdentifier: VF_POSITIONS_ALL_STATUS,
      fieldMetadataUniversalIdentifier: POSITION_STATUS_FIELD_ID,
      position: 4,
      isVisible: true,
      size: 110,
    },
    {
      universalIdentifier: VF_POSITIONS_ALL_HIRING_MGR,
      fieldMetadataUniversalIdentifier: POSITION_HIRING_MANAGER_FIELD_ID,
      position: 5,
      isVisible: true,
      size: 180,
    },
    {
      universalIdentifier: VF_POSITIONS_ALL_OPENED_AT,
      fieldMetadataUniversalIdentifier: POSITION_OPENED_AT_FIELD_ID,
      position: 6,
      isVisible: true,
      size: 140,
    },
    {
      universalIdentifier: VF_POSITIONS_ALL_DESCRIPTION,
      fieldMetadataUniversalIdentifier: POSITION_DESCRIPTION_FIELD_ID,
      position: 7,
      isVisible: true,
      size: 240,
    },
    {
      universalIdentifier: VF_POSITIONS_ALL_SCORING_FRAMEWORK,
      fieldMetadataUniversalIdentifier: POSITION_SCORING_FRAMEWORK_FIELD_ID,
      position: 8,
      isVisible: true,
      size: 200,
    },
    {
      universalIdentifier: VF_POSITIONS_ALL_CREATED_AT,
      fieldMetadataUniversalIdentifier: POSITION_CREATED_AT_FIELD_ID,
      position: 9,
      isVisible: true,
      size: 140,
    },
  ],
});
